### ISSUE TITLE
URLs without an explicit protocol are considered files

### ISSUE THREAD

**Issue by Mr-Wallet** [IonicaBizau/parse-path#16]
Give a short and sweet url like `parseUrl('github.com/IonicaBizau')` and the `resource` comes out fine in 1.3.7... but in 1.3.11, `resource === ""`, because of the fix for file paths. Whoops! It was considered a file path all along... We lucked out in that nothing was relying on the `protocol` field (or perhaps unlucky, as things could not have reached this point if they had). We use `git-url-parse` and we had to lock down its sub-dependencies 2 levels deep to resolve the issue.

It's peculiar that `x.y/z` is assumed to be a file path when `y` is a top-level domain, given that the module is named after parsing _URLs._ Personally, I wouldn't expect file path parsing to be included at the expense of better URL parsing.

Given that providing a protocol for a URL has never been a documented requirement, and given that 1.3.11 has introduced a breaking change for any consumers that didn't particularly care about the returned `protocol`, I'm curious if you'd be receptive to performing a larger version bump which parses more strings as URLs by default (with no protocol available, or perhaps a default)

**Comment by IonicaBizau** [comment]
@Mr-Wallet I see your points here! 👍 I'm going to move the main functionality of this in `parse-path` and then, `parse-url` will be designed specifically for urls.

Let me know if you have other suggestions.

Sorry for inconvenience, I should have been bumping the major tag, but didn't realize that was a breaking change.

Thanks! 🍰

**Comment by IonicaBizau** [comment]
I'm on it! 🚀

**Comment by IonicaBizau** [comment]
So, in [`parse-url`](https://github.com/IonicaBizau/parse-url) the urls are normalized by default. Performance improvements are welcome!
