### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by dzek69** [IonicaBizau/parse-path#28]
This library depends on `querystring` but it's not specified in package.json

**Comment by IonicaBizau** [comment]
Query string is a native package.

**Comment by dzek69** [comment]
This assumes you only want your package to be used in Node environment.
I'm using it with React Native and could want to use it on web with older browsers. But on the other hand - having this installed on Node environment is a waste.

I guess the current behavior is the most right one then.

**Comment by svegan** [comment]
Confirm it's not working with react-native. Requires `querystring` as well as `url`. After installation everything works fine though. But you defentely not expecting this. Come here from parse-url library.

P.S. thanks for your work.
