### ISSUE TITLE
use less dependencies 

### ISSUE THREAD

**Issue by jimmywarting** [IonicaBizau/parse-path#33]
The two dependencies you have on qs & qurerystring... are those two really necessary?
![image](https://user-images.githubusercontent.com/1148376/164903439-c774a425-bb24-48a3-956f-763fcd298661.png)

The pkg becomes quite larger with those two... 
Any possibility that you could just use URL + URLSearchParams instead?

**Comment by IonicaBizau** [comment]
This is addressed in `parse-path@5.0.0`. 🌟 Thank you!
