### ISSUE TITLE
Bug when parsing ios/android deeplinking scheme urls.

### ISSUE THREAD

**Issue by svenlombaert** [IonicaBizau/parse-path#34]
I found some strange behaviour when I'm parsing paths along the lines of: `io.example.dev/this-is-a-path?status=SUCCESS`
When the above is parsed, the `query` will be empty. 

When I'm parsing `io.example.dev/this-is-a-path/with-an-extra-slash?status=SUCCESS`, I do have a `query` object with `status: success` in it.

I have a live example here: https://codesandbox.io/s/parse-path-weird-behavior-rke6mi?file=/src/index.ts
The first url doesn't parse correctly, the others do. 

So it seems there's an extra `/` needed to parse these types of paths/urls (they are used for deeplinking on iOS and Android)

**Comment by IonicaBizau** [comment]
This should be fixed in `parse-path@5.0.0` 🎉
