### ISSUE TITLE
clone urls with numbers in the organisation part are incorrectly treated as port numbers

### ISSUE THREAD

**Issue by richiebres** [IonicaBizau/parse-path#5]
### Repro

`require('parse-url')('git@github.com:9to5/repo.git')`
### Incorrect output:

```
{ protocols: [],
  port: 9,   <==== bug
  resource: 'github.com',
  user: 'git',
  pathname: '/repo.git',
  hash: '',
  search: '',
  href: 'git@github.com:9to5/repo.git' }
```

**Comment by IonicaBizau** [comment]
Thanks for the head's up! Indeed, a bug! :+1: 
Any idea how this format of the ssh url would look like when having a port in it?

**Comment by IonicaBizau** [comment]
I guess #23 fixed this.
